---

#####
## Update apt, upgrade and install dependencies

- name: update and upgrade
  apt:
    update_cache: yes
    upgrade: dist

- name: install dependencies
    name: "{{ item }}"
    state: latest
  with_items:
    - python
    - python-pip
    - python-virtualenv
    - git
    - nginx
    - nginx-extras
    - ansible